import type {Metadata} from 'next'
import {Karla} from 'next/font/google'

import '@/app/globals.css'

const font = Karla({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width,initial-scale=1,maximum-scale=1'
        />
      </head>
      <body className={font.className}>{children}</body>
    </html>
  )
}
